export interface Episode {
  number: number;
  title: string;
  youtubeVideoId: string;
}

export interface Donghua {
  id: string;
  title: string;
  titleCN?: string;
  poster: string;
  genre: string[];
  status: "ongoing" | "completed" | "upcoming";
  episodes: number;
  latestEpisode: number;
  rating: number;
  views: string;
  year: number;
  studio: string;
  synopsis: string;
  youtubeChannel: string;
  episodesList: Episode[];
}

export const allDonghua: Donghua[] = [
  {
    id: "battle-through-the-heavens",
    title: "Battle Through the Heavens",
    titleCN: "斗破苍穹",
    poster: "https://img.youtube.com/vi/n6CWXJGUdHs/maxresdefault.jpg",
    genre: ["Action", "Cultivation", "Fantasy"],
    status: "ongoing",
    episodes: 226,
    latestEpisode: 226,
    rating: 8.5,
    views: "20.1K",
    year: 2018,
    studio: "Shanghai Motion Magic",
    synopsis: "In a land where there is no magic, a young man named Xiao Yan loses everything — his reputation, his powers, and his mother. But when a mysterious ring awakens, he discovers a path to reclaim it all through the ancient art of cultivation.",
    youtubeChannel: "Yuewen Animation",
    episodesList: [
      { number: 1, title: "The Fallen Genius", youtubeVideoId: "n6CWXJGUdHs" },
      { number: 2, title: "Awakening", youtubeVideoId: "GMBBOFsFAkg" },
      { number: 3, title: "The Duel", youtubeVideoId: "kR2DxB7sntA" },
    ],
  },
  {
    id: "soul-land",
    title: "Soul Land",
    titleCN: "斗罗大陆",
    poster: "https://img.youtube.com/vi/VIFhJnFGpCk/maxresdefault.jpg",
    genre: ["Action", "Fantasy", "Cultivation"],
    status: "ongoing",
    episodes: 264,
    latestEpisode: 264,
    rating: 8.8,
    views: "45.2K",
    year: 2018,
    studio: "Sparkly Key Animation",
    synopsis: "Tang San, a prodigy of the hidden Tang Sect, steals forbidden knowledge and is forced to jump off a cliff. Reborn in the Soul Land, he awakens a powerful martial spirit and sets out to become the greatest soul master.",
    youtubeChannel: "Tencent Video Animation",
    episodesList: [
      { number: 1, title: "Rebirth in Soul Land", youtubeVideoId: "VIFhJnFGpCk" },
      { number: 2, title: "The Blue Silver Grass", youtubeVideoId: "tAY5qTBEjF0" },
      { number: 3, title: "Spirit Awakening", youtubeVideoId: "nUGOwHaKuMQ" },
    ],
  },
  {
    id: "immortality",
    title: "Immortality",
    titleCN: "永生",
    poster: "https://img.youtube.com/vi/3B4ajHJhDlY/maxresdefault.jpg",
    genre: ["Cultivation", "Fantasy", "Action"],
    status: "ongoing",
    episodes: 52,
    latestEpisode: 52,
    rating: 8.2,
    views: "15.8K",
    year: 2022,
    studio: "Bilibili",
    synopsis: "Fang Han, a lowly servant, discovers the path of immortal cultivation. Defying the rigid hierarchy of cultivators, he rises through sheer willpower and hidden talent, challenging the very heavens themselves.",
    youtubeChannel: "Made By Bilibili",
    episodesList: [
      { number: 1, title: "The Servant", youtubeVideoId: "3B4ajHJhDlY" },
      { number: 2, title: "First Steps", youtubeVideoId: "W-iQ6E2n-LU" },
    ],
  },
  {
    id: "stellar-transformations",
    title: "Stellar Transformations",
    titleCN: "星辰变",
    poster: "https://img.youtube.com/vi/4R7GLfBDbWQ/maxresdefault.jpg",
    genre: ["Cultivation", "Action", "Fantasy"],
    status: "ongoing",
    episodes: 83,
    latestEpisode: 83,
    rating: 8.0,
    views: "12.4K",
    year: 2020,
    studio: "Shanghai Foch Film",
    synopsis: "Qin Yu, unable to cultivate internal arts, dedicates himself to external martial training. When fate grants him a cosmic treasure, he embarks on a journey across the universe to become a stellar cultivator.",
    youtubeChannel: "Yuewen Animation",
    episodesList: [
      { number: 1, title: "The Path of the Outsider", youtubeVideoId: "4R7GLfBDbWQ" },
      { number: 2, title: "Meteor Tear", youtubeVideoId: "XyMtFIdaCYM" },
    ],
  },
  {
    id: "perfect-world",
    title: "Perfect World",
    titleCN: "完美世界",
    poster: "https://img.youtube.com/vi/m7PbBrOQfMo/maxresdefault.jpg",
    genre: ["Action", "Cultivation", "Fantasy"],
    status: "ongoing",
    episodes: 270,
    latestEpisode: 270,
    rating: 8.3,
    views: "25.6K",
    year: 2021,
    studio: "Shanghai Foch Film",
    synopsis: "Shi Hao, born with supreme bones stolen from him, grows up in a small village. With an unyielding spirit, he cultivates from the weakest to the strongest, facing gods and demons across a perfect world.",
    youtubeChannel: "Tencent Video Animation",
    episodesList: [
      { number: 1, title: "Born of Heaven and Earth", youtubeVideoId: "m7PbBrOQfMo" },
      { number: 2, title: "Supreme Bone", youtubeVideoId: "cIBIL7pMf-s" },
    ],
  },
  {
    id: "against-the-gods",
    title: "Against the Gods",
    titleCN: "逆天邪神",
    poster: "https://img.youtube.com/vi/dESJ7FXl0mY/maxresdefault.jpg",
    genre: ["Action", "Cultivation", "Fantasy"],
    status: "ongoing",
    episodes: 38,
    latestEpisode: 38,
    rating: 8.0,
    views: "18.3K",
    year: 2023,
    studio: "Ruo Hong Culture",
    synopsis: "Yun Che, carrying the memories of a former god, wields the Sky Poison Pearl and Evil God legacy. He journeys through realms, defying fate and crushing anyone who stands in his way.",
    youtubeChannel: "Made By Bilibili",
    episodesList: [
      { number: 1, title: "Reincarnation", youtubeVideoId: "dESJ7FXl0mY" },
      { number: 2, title: "Sky Poison Pearl", youtubeVideoId: "0mQqG5qWlIE" },
    ],
  },
  {
    id: "the-great-ruler",
    title: "The Great Ruler",
    titleCN: "大主宰",
    poster: "https://img.youtube.com/vi/kIWXGP7VxGc/maxresdefault.jpg",
    genre: ["Action", "Fantasy", "Cultivation"],
    status: "ongoing",
    episodes: 74,
    latestEpisode: 74,
    rating: 8.1,
    views: "9.8K",
    year: 2023,
    studio: "Tencent Penguin Pictures",
    synopsis: "Mu Chen, son of the Spiritual Emperor, enters the Northern Spiritual Academy. With the Great Sumeru Heavenly Art and the mysterious Nine Netherworld Bird, he charts his path to become the supreme ruler.",
    youtubeChannel: "iQIYI Animation",
    episodesList: [
      { number: 1, title: "Northern Spiritual Realm", youtubeVideoId: "kIWXGP7VxGc" },
      { number: 2, title: "Spiritual Academy", youtubeVideoId: "FIBAZLq9mKw" },
    ],
  },
  {
    id: "rakshasa-street",
    title: "Rakshasa Street",
    titleCN: "镇魂街",
    poster: "https://img.youtube.com/vi/0CfUvFEPSds/maxresdefault.jpg",
    genre: ["Action", "Supernatural", "Fantasy"],
    status: "completed",
    episodes: 24,
    latestEpisode: 24,
    rating: 8.4,
    views: "14.2K",
    year: 2016,
    studio: "L² Studio",
    synopsis: "Xia Ling, an ordinary college student, discovers she is a Spirit General keeper. Alongside the fierce warrior Cao Yan Bing, she battles evil spirits threatening to destroy the boundary between the living and the dead.",
    youtubeChannel: "Made By Bilibili",
    episodesList: [
      { number: 1, title: "The Spirit General", youtubeVideoId: "0CfUvFEPSds" },
      { number: 2, title: "Guardian of Rakshasa Street", youtubeVideoId: "rFqGRkfjVjA" },
    ],
  },
  {
    id: "renegade-immortal",
    title: "Renegade Immortal",
    titleCN: "仙逆",
    poster: "https://img.youtube.com/vi/2AKmXESfbso/maxresdefault.jpg",
    genre: ["Cultivation", "Action", "Drama"],
    status: "ongoing",
    episodes: 52,
    latestEpisode: 52,
    rating: 8.5,
    views: "9.9K",
    year: 2023,
    studio: "Ruo Hong Culture",
    synopsis: "Wang Lin, a mortal with average talent, is thrust into the world of cultivation after a chance encounter. His path is one of defiance — against fate, sects, and even the heavens themselves.",
    youtubeChannel: "Made By Bilibili",
    episodesList: [
      { number: 1, title: "A Mortal's Path", youtubeVideoId: "2AKmXESfbso" },
      { number: 2, title: "Clay Dragon", youtubeVideoId: "XPBjSvWqgLc" },
    ],
  },
  {
    id: "a-will-eternal",
    title: "A Will Eternal",
    titleCN: "一念永恒",
    poster: "https://img.youtube.com/vi/b3FfOOWR-Gw/maxresdefault.jpg",
    genre: ["Cultivation", "Comedy", "Action"],
    status: "completed",
    episodes: 52,
    latestEpisode: 52,
    rating: 8.3,
    views: "11.5K",
    year: 2022,
    studio: "Bilibili",
    synopsis: "Bai Xiaochun, a cowardly boy obsessed with living forever, enters a cultivation sect. His comedic journey through pills, sect politics, and cosmic battles reveals a hero nobody expected.",
    youtubeChannel: "Made By Bilibili",
    episodesList: [
      { number: 1, title: "The Fear of Death", youtubeVideoId: "b3FfOOWR-Gw" },
      { number: 2, title: "Spirit Creek Sect", youtubeVideoId: "yX_RxPB_mXc" },
    ],
  },
  {
    id: "coiling-dragon",
    title: "Coiling Dragon",
    titleCN: "盘龙",
    poster: "https://img.youtube.com/vi/GBywLkRjNUk/maxresdefault.jpg",
    genre: ["Cultivation", "Action", "Fantasy"],
    status: "ongoing",
    episodes: 6,
    latestEpisode: 6,
    rating: 7.8,
    views: "6.2K",
    year: 2024,
    studio: "Tencent Penguin Pictures",
    synopsis: "Linley Baruch, a fallen noble, discovers the Coiling Dragon Ring — an artifact of immense power. Through training and war, he ascends through the Four Higher Planes to become a sovereign.",
    youtubeChannel: "Tencent Video Animation",
    episodesList: [
      { number: 1, title: "The Fallen Clan", youtubeVideoId: "GBywLkRjNUk" },
    ],
  },
  {
    id: "fog-hill-of-five-elements",
    title: "Fog Hill of Five Elements",
    titleCN: "雾山五行",
    poster: "https://img.youtube.com/vi/GCYJEFBcDNk/maxresdefault.jpg",
    genre: ["Action", "Fantasy", "Supernatural"],
    status: "ongoing",
    episodes: 10,
    latestEpisode: 10,
    rating: 9.0,
    views: "22.1K",
    year: 2020,
    studio: "Samsara Studio",
    synopsis: "In a mystical land sealed by five elemental guardians, a demon breaks free. One young warrior must master all five elements to prevent the apocalypse — but power comes at a terrible cost.",
    youtubeChannel: "Made By Bilibili",
    episodesList: [
      { number: 1, title: "The Seal Breaks", youtubeVideoId: "GCYJEFBcDNk" },
    ],
  },
  {
    id: "scissor-seven",
    title: "Scissor Seven",
    titleCN: "刺客伍六七",
    poster: "https://img.youtube.com/vi/GcY-6RfqDLY/maxresdefault.jpg",
    genre: ["Comedy", "Action", "Slice of Life"],
    status: "ongoing",
    episodes: 40,
    latestEpisode: 40,
    rating: 8.7,
    views: "31.4K",
    year: 2018,
    studio: "Sharefun Studio",
    synopsis: "Seven, an amnesiac assassin with terrible skills and a pair of talking scissors, takes on ridiculous hit jobs while slowly uncovering his mysterious past.",
    youtubeChannel: "Made By Bilibili",
    episodesList: [
      { number: 1, title: "The Worst Assassin", youtubeVideoId: "GcY-6RfqDLY" },
    ],
  },
  {
    id: "link-click",
    title: "Link Click",
    titleCN: "时光代理人",
    poster: "https://img.youtube.com/vi/2OmuinTqKwQ/maxresdefault.jpg",
    genre: ["Sci-Fi", "Drama", "Supernatural"],
    status: "completed",
    episodes: 23,
    latestEpisode: 23,
    rating: 9.1,
    views: "38.7K",
    year: 2021,
    studio: "Haoliners Animation",
    synopsis: "Cheng Xiaoshi and Lu Guang run a photo studio with a secret — they can dive into photographs to relive moments in time. But every change in the past has consequences they cannot predict.",
    youtubeChannel: "Made By Bilibili",
    episodesList: [
      { number: 1, title: "Emma", youtubeVideoId: "2OmuinTqKwQ" },
      { number: 2, title: "The Price of Regret", youtubeVideoId: "FOCi3aPYmYs" },
    ],
  },
  {
    id: "swallowed-star",
    title: "Swallowed Star",
    titleCN: "吞噬星空",
    poster: "https://img.youtube.com/vi/TPnqEvjLGbQ/maxresdefault.jpg",
    genre: ["Sci-Fi", "Action", "Cultivation"],
    status: "ongoing",
    episodes: 156,
    latestEpisode: 156,
    rating: 8.2,
    views: "16.9K",
    year: 2020,
    studio: "Shanghai Foch Film",
    synopsis: "After a virus transforms Earth, humanity faces mutated beasts and expanding wilderness. Luo Feng, an ordinary young man, awakens a spiritual force that could save humanity — or destroy it.",
    youtubeChannel: "Tencent Video Animation",
    episodesList: [
      { number: 1, title: "The RR Virus", youtubeVideoId: "TPnqEvjLGbQ" },
    ],
  },
  {
    id: "throne-of-seal",
    title: "Throne of Seal",
    titleCN: "神印王座",
    poster: "https://img.youtube.com/vi/7jYtGMVWIpk/maxresdefault.jpg",
    genre: ["Action", "Fantasy", "Cultivation"],
    status: "ongoing",
    episodes: 130,
    latestEpisode: 130,
    rating: 8.1,
    views: "13.4K",
    year: 2022,
    studio: "Sparkly Key Animation",
    synopsis: "Long Haochen, born with a crippled spiritual stove, trains to become a knight in a world overrun by demons. His determination and hidden talent could make him the youngest Divine Knight.",
    youtubeChannel: "iQIYI Animation",
    episodesList: [
      { number: 1, title: "The Knight's Test", youtubeVideoId: "7jYtGMVWIpk" },
    ],
  },
  {
    id: "martial-universe",
    title: "Martial Universe",
    titleCN: "武动乾坤",
    poster: "https://img.youtube.com/vi/KL-zkX3rrG4/maxresdefault.jpg",
    genre: ["Action", "Cultivation", "Fantasy"],
    status: "ongoing",
    episodes: 96,
    latestEpisode: 96,
    rating: 7.9,
    views: "8.7K",
    year: 2020,
    studio: "Shanghai Motion Magic",
    synopsis: "Lin Dong, a young man from a declining family, discovers a mysterious stone talisman. With it, he embarks on a journey through martial arts mastery, ancient ruins, and cosmic battles.",
    youtubeChannel: "Tencent Video Animation",
    episodesList: [
      { number: 1, title: "The Stone Talisman", youtubeVideoId: "KL-zkX3rrG4" },
    ],
  },
  {
    id: "apotheosis",
    title: "Apotheosis",
    titleCN: "百炼成神",
    poster: "https://img.youtube.com/vi/lTh74a-zA6Q/maxresdefault.jpg",
    genre: ["Cultivation", "Action", "Fantasy"],
    status: "ongoing",
    episodes: 104,
    latestEpisode: 104,
    rating: 7.7,
    views: "7.3K",
    year: 2022,
    studio: "iQIYI",
    synopsis: "Luo Zheng, once a genius young lord, is reduced to a servant after his family falls. Armed with a mysterious scroll, he cultivates his way through impossible odds to reach godhood.",
    youtubeChannel: "YOUKU Animation",
    episodesList: [
      { number: 1, title: "Fallen Noble", youtubeVideoId: "lTh74a-zA6Q" },
    ],
  },
  {
    id: "heaven-officials-blessing",
    title: "Heaven Official's Blessing",
    titleCN: "天官赐福",
    poster: "https://img.youtube.com/vi/FdBz8VhNdO0/maxresdefault.jpg",
    genre: ["Fantasy", "Action", "Supernatural"],
    status: "completed",
    episodes: 23,
    latestEpisode: 23,
    rating: 8.9,
    views: "28.5K",
    year: 2020,
    studio: "Haoliners Animation",
    synopsis: "Xie Lian, a prince who ascended to heaven twice and was banished twice, meets the mysterious Hua Cheng. Together they unravel divine conspiracies and ghostly mysteries spanning 800 years.",
    youtubeChannel: "Made By Bilibili",
    episodesList: [
      { number: 1, title: "The Crown Prince", youtubeVideoId: "FdBz8VhNdO0" },
    ],
  },
  {
    id: "the-outcast",
    title: "The Outcast",
    titleCN: "一人之下",
    poster: "https://img.youtube.com/vi/v0bZxOyFpcU/maxresdefault.jpg",
    genre: ["Action", "Supernatural", "Martial Arts"],
    status: "completed",
    episodes: 48,
    latestEpisode: 48,
    rating: 8.0,
    views: "10.2K",
    year: 2016,
    studio: "Tencent Penguin Pictures",
    synopsis: "Zhang Chulan, an ordinary college student, discovers his grandfather was part of a hidden world of supernatural martial artists. When dark forces target him, he must unlock his family's secrets.",
    youtubeChannel: "Tencent Video Animation",
    episodesList: [
      { number: 1, title: "The Grandfather's Secret", youtubeVideoId: "v0bZxOyFpcU" },
    ],
  },
  {
    id: "the-demon-hunter",
    title: "The Demon Hunter",
    titleCN: "斗罗大陆",
    poster: "https://img.youtube.com/vi/QhYBPqjKqUk/maxresdefault.jpg",
    genre: ["Action", "Supernatural", "Fantasy"],
    status: "ongoing",
    episodes: 78,
    latestEpisode: 78,
    rating: 9.0,
    views: "19.7K",
    year: 2023,
    studio: "Bilibili",
    synopsis: "In a world plagued by demons, a young hunter with mysterious bloodline powers takes on the deadliest creatures. Each battle reveals a deeper conspiracy threatening all of humanity.",
    youtubeChannel: "Made By Bilibili",
    episodesList: [
      { number: 1, title: "Blood of the Hunter", youtubeVideoId: "QhYBPqjKqUk" },
    ],
  },
  {
    id: "way-of-choices",
    title: "Way of Choices",
    titleCN: "择天记",
    poster: "https://img.youtube.com/vi/5I9KOpT_3Jo/maxresdefault.jpg",
    genre: ["Cultivation", "Action", "Romance"],
    status: "ongoing",
    episodes: 19,
    latestEpisode: 19,
    rating: 9.0,
    views: "35.8K",
    year: 2024,
    studio: "Tencent Penguin Pictures",
    synopsis: "Chen Chang Sheng, a boy destined to die young, leaves his monastery to change his fate. Through the Grand Trials and cultivation, he challenges the heavens and the dark forces behind them.",
    youtubeChannel: "Tencent Video Animation",
    episodesList: [
      { number: 1, title: "The Fated Boy", youtubeVideoId: "5I9KOpT_3Jo" },
    ],
  },
  {
    id: "sword-of-coming",
    title: "Sword of Coming",
    titleCN: "剑来",
    poster: "https://img.youtube.com/vi/SRcCfOHBnMY/maxresdefault.jpg",
    genre: ["Cultivation", "Action", "Fantasy"],
    status: "ongoing",
    episodes: 52,
    latestEpisode: 52,
    rating: 8.6,
    views: "12.3K",
    year: 2024,
    studio: "Bilibili",
    synopsis: "Chen Ping'an, a young boy from a remote village, is drawn into the vast world of sword cultivation. With a mysterious old sword and unwavering resolve, he walks the path no one dares tread.",
    youtubeChannel: "Made By Bilibili",
    episodesList: [
      { number: 1, title: "The Village Boy", youtubeVideoId: "SRcCfOHBnMY" },
    ],
  },
  {
    id: "100000-years-refining-qi",
    title: "100,000 Years of Refining Qi",
    titleCN: "十万年炼气",
    poster: "https://img.youtube.com/vi/fLDvJ6pKZsM/maxresdefault.jpg",
    genre: ["Cultivation", "Comedy", "Fantasy"],
    status: "ongoing",
    episodes: 342,
    latestEpisode: 342,
    rating: 7.5,
    views: "8.9K",
    year: 2022,
    studio: "Tencent",
    synopsis: "A sect master has been stuck at the first level of cultivation for 100,000 years. His pets, disciples, and even the sect's chickens have become immortals — but he might secretly be the strongest being alive.",
    youtubeChannel: "Tencent Video Animation",
    episodesList: [
      { number: 1, title: "The Stubborn Cultivator", youtubeVideoId: "fLDvJ6pKZsM" },
    ],
  },
  {
    id: "big-brother",
    title: "Big Brother",
    titleCN: "师兄啊师兄",
    poster: "https://img.youtube.com/vi/o1LMFJXQLL0/maxresdefault.jpg",
    genre: ["Comedy", "Cultivation", "Action"],
    status: "ongoing",
    episodes: 142,
    latestEpisode: 142,
    rating: 8.0,
    views: "11.6K",
    year: 2023,
    studio: "Shanghai Motion Magic",
    synopsis: "Li Chang Shou, a cautious immortal cultivator, tries to live a quiet life. But fate keeps throwing him into dangerous situations where his hidden power turns him into an unexpected hero.",
    youtubeChannel: "Made By Bilibili",
    episodesList: [
      { number: 1, title: "The Careful Immortal", youtubeVideoId: "o1LMFJXQLL0" },
    ],
  },
  {
    id: "ever-night",
    title: "Ever Night",
    titleCN: "将夜",
    poster: "https://img.youtube.com/vi/XfMI5S1Cj2U/maxresdefault.jpg",
    genre: ["Action", "Fantasy", "Cultivation"],
    status: "ongoing",
    episodes: 6,
    latestEpisode: 6,
    rating: 8.0,
    views: "5.4K",
    year: 2024,
    studio: "Tencent Penguin Pictures",
    synopsis: "Ning Que, a young soldier with a mysterious past, and his servant Sang Sang navigate a world where the coming of 'Ever Night' signals the end of civilization. Dark prophecies swirl around Sang Sang.",
    youtubeChannel: "Tencent Video Animation",
    episodesList: [
      { number: 1, title: "The Soldier and the Girl", youtubeVideoId: "XfMI5S1Cj2U" },
    ],
  },
  {
    id: "tomb-of-fallen-gods",
    title: "Tomb of Fallen Gods",
    titleCN: "神墓",
    poster: "https://img.youtube.com/vi/pEH3gQBkbzA/maxresdefault.jpg",
    genre: ["Action", "Fantasy", "Supernatural"],
    status: "ongoing",
    episodes: 43,
    latestEpisode: 43,
    rating: 9.0,
    views: "17.5K",
    year: 2024,
    studio: "Bilibili",
    synopsis: "A young man awakens in a tomb of gods with no memory. As he pieces together his past, he discovers he may be connected to an ancient war between mortals and deities.",
    youtubeChannel: "Made By Bilibili",
    episodesList: [
      { number: 1, title: "Awakening in the Tomb", youtubeVideoId: "pEH3gQBkbzA" },
    ],
  },
  {
    id: "other-side-of-deep-space",
    title: "The Other Side of Deep Space",
    titleCN: "深空彼岸",
    poster: "https://img.youtube.com/vi/gnPjPVFaV8Y/maxresdefault.jpg",
    genre: ["Sci-Fi", "Action", "Fantasy"],
    status: "ongoing",
    episodes: 21,
    latestEpisode: 21,
    rating: 9.0,
    views: "8.1K",
    year: 2024,
    studio: "Bilibili",
    synopsis: "When Earth's barrier weakens, otherworldly dimensions begin merging with reality. A young man discovers he can navigate between these dimensions, uncovering truths about the universe's origins.",
    youtubeChannel: "Made By Bilibili",
    episodesList: [
      { number: 1, title: "The Barrier Breaks", youtubeVideoId: "gnPjPVFaV8Y" },
    ],
  },
  {
    id: "in-search-of-gods",
    title: "In Search of Gods",
    titleCN: "寻神记",
    poster: "https://img.youtube.com/vi/TsGYj51ADqE/maxresdefault.jpg",
    genre: ["Cultivation", "Fantasy", "Action"],
    status: "ongoing",
    episodes: 11,
    latestEpisode: 11,
    rating: 9.5,
    views: "6.8K",
    year: 2024,
    studio: "Bilibili",
    synopsis: "A wandering cultivator seeks the truth about the gods who abandoned the mortal realm. His journey takes him through forbidden lands, ancient ruins, and battles with beings of unimaginable power.",
    youtubeChannel: "Made By Bilibili",
    episodesList: [
      { number: 1, title: "The Wanderer", youtubeVideoId: "TsGYj51ADqE" },
    ],
  },
  {
    id: "urban-miracle-doctor",
    title: "Urban Miracle Doctor",
    titleCN: "都市神医",
    poster: "https://img.youtube.com/vi/XsB2ldivKmA/maxresdefault.jpg",
    genre: ["Action", "Drama", "Modern"],
    status: "ongoing",
    episodes: 176,
    latestEpisode: 176,
    rating: 9.5,
    views: "14.3K",
    year: 2023,
    studio: "Tencent",
    synopsis: "A young doctor with mysterious medical skills returns to the city after years of training in the mountains. Using ancient techniques and modern knowledge, he cures the incurable and uncovers dark conspiracies.",
    youtubeChannel: "Tencent Video Animation",
    episodesList: [
      { number: 1, title: "Return to the City", youtubeVideoId: "XsB2ldivKmA" },
    ],
  },
  {
    id: "yun-shen-buzhi-meng",
    title: "Yun Shen Buzhi Meng",
    titleCN: "云深不知梦",
    poster: "https://img.youtube.com/vi/4-CxoBGzBG4/maxresdefault.jpg",
    genre: ["Fantasy", "Romance", "Supernatural"],
    status: "ongoing",
    episodes: 12,
    latestEpisode: 12,
    rating: 8.0,
    views: "4.2K",
    year: 2024,
    studio: "Bilibili",
    synopsis: "A young woman trapped in a dream world meets a mysterious cultivator. Together they navigate layers of illusion and reality, uncovering a love story that spans lifetimes.",
    youtubeChannel: "Made By Bilibili",
    episodesList: [
      { number: 1, title: "Dreamscape", youtubeVideoId: "4-CxoBGzBG4" },
    ],
  },
  {
    id: "martial-god-asura",
    title: "Martial God Asura",
    titleCN: "修罗武神",
    poster: "https://img.youtube.com/vi/wOA3yPlkbO0/maxresdefault.jpg",
    genre: ["Action", "Cultivation", "Fantasy"],
    status: "ongoing",
    episodes: 64,
    latestEpisode: 64,
    rating: 7.8,
    views: "9.1K",
    year: 2023,
    studio: "Shanghai Motion Magic",
    synopsis: "Chu Feng, an outcast disciple, awakens the legendary Asura Spirit. With newfound power and an unbreakable will, he rises from nothing to challenge the strongest cultivators across all realms.",
    youtubeChannel: "Made By Bilibili",
    episodesList: [
      { number: 1, title: "The Outcast Disciple", youtubeVideoId: "wOA3yPlkbO0" },
    ],
  },
];

export const featuredDonghua = allDonghua.filter((d) =>
  ["battle-through-the-heavens", "fog-hill-of-five-elements", "link-click", "soul-land", "the-demon-hunter"].includes(d.id)
);

export const topPopular = [
  { rank: 1, title: "Way of Choices", views: "35.8K", rating: 9.0 },
  { rank: 2, title: "Battle Through the Heavens", views: "20.1K", rating: 8.5 },
  { rank: 3, title: "Sword of Coming", views: "12.3K", rating: 8.6 },
  { rank: 4, title: "Renegade Immortal", views: "9.9K", rating: 8.5 },
  { rank: 5, title: "Beyond Time's Gaze", views: "4.6K", rating: 8.0 },
];
